"""empty message

Revision ID: 453bbaa0a5fb
Revises: f2f8aa5c3050
Create Date: 2018-05-15 19:47:40.530147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453bbaa0a5fb'
down_revision = 'f2f8aa5c3050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProxyManager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proxyName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LoginUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('proxyManager', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proxyManager'], ['ProxyManager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_model')
    op.drop_table('test_model2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_model_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('test_model_password', sa.VARCHAR(length=64), nullable=True),
    sa.Column('a', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['a'], ['test_model2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LoginUser')
    op.drop_table('ProxyManager')
    # ### end Alembic commands ###
