"""empty message

Revision ID: f2f8aa5c3050
Revises: 
Create Date: 2018-05-15 18:46:05.278450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f8aa5c3050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_model2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_model_username', sa.String(length=64), nullable=True),
    sa.Column('test_model_password', sa.String(length=64), nullable=True),
    sa.Column('a', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a'], ['test_model2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    op.drop_table('test_model2')
    op.drop_table('User')
    # ### end Alembic commands ###
